# Generated by Django 4.2.4 on 2023-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='no_image_available.jpg', upload_to=''),
        ),
    ]
