# Generated by Django 4.2.4 on 2023-09-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0002_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reviewer_id', models.BigIntegerField()),
                ('reviewed_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=5)),
                ('reviewed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REVIEWED', to='contenttypes.contenttype')),
                ('reviewer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REVIEWER', to='contenttypes.contenttype')),
            ],
        ),
    ]
