# Generated by Django 4.2.4 on 2023-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_item_price_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Customer', 'Customer'), ('Pilot', 'Pilot'), ('TBD', 'TBD')], default='TBD', max_length=10),
        ),
    ]
