# Generated by Django 4.2.4 on 2023-09-11 08:43

import database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_basketitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[database.validators.rating_validator]),
        ),
    ]
