# Generated by Django 4.2.4 on 2023-09-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.AddField(
            model_name='person',
            name='n_raters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
