# Generated by Django 4.2.4 on 2023-09-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_order_rating_person_n_raters_person_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_completed',
            new_name='date_concluded',
        ),
    ]
