# Generated by Django 4.2.4 on 2023-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_rename_date_completed_order_date_concluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pilot',
            name='n_drops',
            field=models.IntegerField(default=0),
        ),
    ]
