# Generated by Django 4.2.4 on 2023-09-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_review_taken_in_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(default='no_image_available.jpg', upload_to=''),
        ),
    ]
