# Generated by Django 4.2.4 on 2023-09-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_seller_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='taken_in_calculation',
        ),
    ]
